version: '3.8'

services:
  front-end:
    build:
      context: .
    ports:
      - "5173:5173"  # Mapea el puerto 5173 de tu máquina local al contenedor
    volumes:
      - ./src:/app/src  # Esto permitirá que los cambios locales se reflejen en el contenedor
    env_file:
      - .env  # Cargar las variables de entorno del archivo .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
